import Text from '@/components/Text/Text'
import React from 'react'

const LitePaper = () => {
    return (
        <>
            <section className='flex flex-col container 2xl:max-w-[1280px] px-6 h-screen mx-auto border-b-2 border-sacramento-green py-20 overflow-x-hidden'>
                <div className='flex items-center justify-between'>
                    <div className='flex flex-col gap-4'>
                        <Text variant='8xl' className='font-black' font='font-satoshi' color='text-white'>SITTARIS</Text>
                        <Text variant='4xl' className='font-semibold' font='font-spring' color='text-white'>PURE BITCOIN ENERGY</Text>
                    </div>
                    <img alt='logo' src='logo-with-url.png' className='xl:h-[30vh] h-[15vh] object-contain' />
                </div>
                <div className='mx-auto flex flex-col items-center gap-8 mt-auto'>
                    <Text variant='8xl' className='font-black' font='font-satoshi'>LITE PAPER</Text>
                    <div className='flex items-center justify-around gap-24'>
                        <Text variant='4xl' className='font-semibold' font='font-satoshi'>ZERO - EMISSION</Text>
                        <Text variant='4xl' className='font-semibold' font='font-satoshi'>ZERO - WASTE</Text>
                        <Text variant='4xl' className='font-semibold' font='font-satoshi'>PURE ENERGY</Text>
                    </div>
                </div>
            </section>
            <section className='container 2xl:max-w-[1280px] px-6 mx-auto flex flex-col pt-20'>
                <div className='relative flex flex-col pr-32'>
                    <div className='absolute w-screen top-0 left-1/2 -translate-x-1/2 -z-10'>
                        <div className='relative w-full'>
                            <img alt='leaf' src='leaf-1.png' className='absolute w-[15%] max-w-[250px] top-0 right-0' />
                        </div>
                    </div>
                    <Text variant='4xl' className='font-semibold uppercase' font='font-spring'>Abstract</Text>
                    <Text variant='2xl' className='font-medium mt-6'>
                        The Sittaris project is an initiative aimed at revolutionizing the sustainability, energy efficiency, and solar energy sectors. With global warming and the escalating energy demands of Bitcoin mining in mind, our platform introduces a novel approach to renewable energy funding and governance through tokenization. By leveraging blockchain technology and the power of
                        community-driven decision-making, we are set to drive the transition towards cleaner and more efficient energy sources. This litepaper outlines the core principles, functionalities, and benefits of our project.
                    </Text>

                    <Text variant='4xl' className='font-semibold mt-[72px] uppercase' font='font-spring'>Introduction</Text>
                    <Text variant='2xl' className='font-medium mt-6'>
                        In essence, the Sittaris project aims to tokenize energy produced by solar panels, which is then used to power Bitcoin mining operations, as well as creating verifiable green energy. Furthermore, the project aims to use heat generated by the Bitcoin mining operations to power greenhouses and more.
                    </Text>
                    <Text variant='2xl' className='font-medium mt-6'>
                        The urgency of addressing global warming and the escalating energy demands of Bitcoin mining cannot be overstated. Traditional solutions fall short in ensuring a sustainable and eco-conscious future. The Sittaris project envisions a world where renewable energy sources are not only accessible but also democratically controlled. By tokenizing solar parks, we allow individuals to become active participants in the green energy revolution.
                    </Text>
                </div>

                <Text variant='4xl' className='font-semibold mt-[72px] uppercase' font='font-spring'>Project Overview</Text>
                <Text variant='2xl' className='font-medium mt-6'>
                    The aim of the project is to build an ecosystem around sustainable investment opportunities backed by renewable energy sources. With a track record of launching successful solar energy projects and many more parks in the pipeline, we&apos;re poised for growth.
                </Text>

                <Text variant='2xl' className='font-semibold mt-10' font='font-spring'>Token overview</Text>
                <Text variant='2xl' className='font-medium mt-4'>
                    Our project introduces a dual-purpose token:
                </Text>
                <Text variant='2xl' className='font-medium mt-6'>
                    <b>Governance token:</b> This token empowers holders to participate in decision-making processes related to new solar park developments, expansions, mining operations, and more. It serves as the backbone of our decentralized ecosystem, where the community shapes the project&apos;s future.
                </Text>
                <Text variant='2xl' className='font-medium mt-4'>
                    <b>Utility token:</b> The utility token is essential for accessing various services within the ecosystem, including Proof of Energy (POE) dashboards and analytics. It is also required for participation in staking and rewards programs.
                </Text>

                <div className='relative flex flex-col pl-32'>
                    <div className='absolute w-screen top-0 left-1/2 -translate-x-1/2 -z-10'>
                        <div className='relative w-full'>
                            <img alt='leaf' src='leaf-2.png' className='absolute w-[15%] max-w-[250px] top-0 left-0' />
                        </div>
                    </div>
                    <Text variant='2xl' className='font-semibold mt-10' font='font-spring'>Genesis pool and initial solar park launch</Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        The initial sale of governance tokens will create the &quot;genesis pool.&quot; This pool will be the catalyst for the launch of solar parks in the Netherlands, marking the beginning of our journey towards a sustainable future.
                    </Text>

                    <Text variant='2xl' className='font-semibold mt-10' font='font-spring'>Energy monetization</Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        The energy generated in these solar parks will be harnessed and monetized in several innovative ways:
                    </Text>
                    <Text variant='2xl' className='font-medium mt-6'>
                        <b>Proof of Energy (POE) - Trustless verification of energy source:</b> This trustless verification system ensures complete transparency and accountability in the source and quantity of energy used for Bitcoin mining. This not only establishes credibility within the crypto community but also aligns with global efforts to shift towards sustainable energy practices.
                    </Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        <b>BTC mining operations:</b> The power generated by the solar parks will power Bitcoin mining operations, contributing to the growth of the Bitcoin ecosystem while promoting clean energy.
                    </Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        <b>Heat recycling for greenhouses:</b> The excess heat produced by the mining containers will be captured and recycled to power greenhouses, promoting sustainable agriculture.
                    </Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        <b>Excess energy storage and resale:</b> Surplus energy may be stored in batteries or sold back to the grid, maximizing the utilization of clean energy resources and contributing to grid stability.
                    </Text>

                    <Text variant='2xl' className='font-semibold mt-10' font='font-spring'>Circular economy model</Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        Our project is designed to create a self-sustaining circular economy:
                    </Text>
                    <Text variant='2xl' className='font-medium mt-6'>
                        <b>Profits reinvestment:</b> A portion of the profits generated from energy monetization will be reinvested into the genesis pool to facilitate the launch of more solar parks.
                    </Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        <b>Buyback and make model:</b> An automated market maker will be used to leverage the financial benefits of buybacks and issuance without the drawbacks of burning and without perpetually increasing token supply. We can do this with a protocol treasury implemented as a network-owned Balancer “smart pool” that serves as an automatic buyback machine, token issuance pool, and liquidity provider.
                    </Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        <b>Staking and rewards:</b> Tokens bought back will be reintroduced into the ecosystem through staking and rewards programs, encouraging community participation and engagement.
                    </Text>
                </div>

                <div className='relative flex flex-col pr-32'>
                    <div className='absolute w-screen top-0 left-1/2 -translate-x-1/2 -z-10'>
                        <div className='relative w-full'>
                            <img alt='leaf' src='leaf-1.png' className='absolute w-[15%] max-w-[250px] top-0 right-0' />
                        </div>
                    </div>
                    <Text variant='2xl' className='font-semibold mt-10' font='font-spring'>Market potential</Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        The Sittaris project operates at the intersection of two rapidly growing sectors: renewable energy and the cryptocurrency market. This convergence presents a substantial market potential for investors seeking sustainable returns.
                    </Text>

                    <Text variant='2xl' className='font-black mt-6'>
                        Renewable energy sector:
                    </Text>
                    <ul className='mt-4 list-inside list-disc'>
                        <li className='list-item'>
                            <Text variant='2xl' className='font-medium mt-6'>
                                <b>Global renewable energy market size:</b> The global renewable energy market is estimated to be worth $3.6 trillion by 2030, with an annual growth rate of 15.4%. The increasing adoption of clean energy sources and stringent environmental regulations drive this growth.
                            </Text>
                        </li>
                        <li className='list-item'>
                            <Text variant='2xl' className='font-medium mt-6'>
                                <b>Solar energy segment:</b> Within the renewable energy sector, solar energy accounts for a significant share. Solar installations are projected to increase by 15% annually, reaching £608 billion by 2030. Sittaris positions investors to capitalize on this solar energy boom.
                            </Text>
                        </li>
                    </ul>

                    <Text variant='2xl' className='font-black mt-6'>
                        Renewable energy sector:
                    </Text>
                    <ul className='mt-4 list-inside list-disc'>
                        <li className='list-item'>
                            <Text variant='2xl' className='font-medium mt-6'>
                                <b>Total crypto market capitalization:</b> The total market capitalization of cryptocurrencies currently stands at $5.1 billion. Bitcoin, the leading cryptocurrency, continues to be a prominent investment choice for institutional and retail investors.
                            </Text>
                        </li>
                        <li className='list-item'>
                            <Text variant='2xl' className='font-medium mt-6'>
                                <b>Green crypto investments:</b> The demand for eco-friendly and sustainable cryptocurrency investments is on the rise. Investors increasingly seek projects that align with responsible environmental practices, creating a niche market for projects like Sittaris.
                            </Text>
                        </li>
                    </ul>
                </div>

                <div className='relative flex flex-col pl-32 pb-20'>
                    <div className='absolute w-screen h-full top-0 left-1/2 -translate-x-1/2 -z-10 overflow-hidden'>
                        <div className='relative w-full'>
                            <img alt='leaf' src='leaf-2.png' className='absolute w-[15%] max-w-[250px] top-0 left-0' />
                        </div>
                    </div>
                    <Text variant='2xl' className='font-medium mt-10'>
                        Sittaris bridges the gap between the renewable energy and cryptocurrency sectors, and along with the growing demand for sustainable crypto investments, suggests a significant opportunity for Sittaris investors. Our unique offering positions us to capture a substantial share of this emerging market, offering both sustainable returns and a positive environmental impact.
                    </Text>

                    <Text variant='4xl' className='font-semibold uppercase mt-[72px]' font='font-spring'>Conclusion</Text>
                    <Text variant='2xl' className='font-medium mt-6'>
                        The Sittaris project is a pioneering initiative that combines sustainability, energy efficiency, and blockchain technology to create a brighter and cleaner future. By actively involving the community in decision-making and leveraging the power of renewable energy, we are on a mission to revolutionize the way we generate, use, and think about clean energy. Join us in shaping a more sustainable tomorrow.
                    </Text>

                    <Text variant='2xl' className='font-semibold mt-10' font='font-spring'>Disclaimer</Text>
                    <Text variant='2xl' className='font-medium mt-4'>
                        This litepaper provides an overview of the Sittaris project&apos;s vision and approach. Specific technical details, partnerships, and developments will be available in our whitepaper and ongoing project updates.
                    </Text>
                </div>
            </section>
        </>
    )
}

export default LitePaper